//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gayaduttsingh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class register
    {
        public string fname { get; set; }
        public string lname { get; set; }
        public string father { get; set; }
        public string gender { get; set; }
        public string dob { get; set; }
        public string school { get; set; }
        public string standard { get; set; }
        public string mob { get; set; }
        public string caddr { get; set; }
        public string profile { get; set; }
        public string email { get; set; }
        public string passwd { get; set; }
        public string regdt { get; set; }
    }
}
